/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    books: Book;
    'book-chapters': BookChapter;
    authors: Author;
    publishers: Publisher;
    categories: Category;
    series: Series;
    lists: List;
    'blog-posts': BlogPost;
    pages: Page;
    reviews: Review;
    media: Media;
    'evidence-files': EvidenceFile;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    books: BooksSelect<false> | BooksSelect<true>;
    'book-chapters': BookChaptersSelect<false> | BookChaptersSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    publishers: PublishersSelect<false> | PublishersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    series: SeriesSelect<false> | SeriesSelect<true>;
    lists: ListsSelect<false> | ListsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'evidence-files': EvidenceFilesSelect<false> | EvidenceFilesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'affiliate-settings': AffiliateSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'affiliate-settings': AffiliateSettingsSelect<false> | AffiliateSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Every book page on the site. A draft stays off the live site, and a publish date in the future holds a published book back until that date passes. The rule that trips people up: the rights tier decides what the page may offer, and an in-copyright book can never carry a PDF — saving one that does will fail.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: number;
  /**
   * বাংলা শিরোনাম — the <h1> and the headline in search results, e.g. "অপেক্ষা".
   */
  title: string;
  /**
   * Transliteration, e.g. "Opekkha". Feeds Banglish search and the OG card. Not shown on the page.
   */
  titleLatin?: string | null;
  /**
   * One-line summary shown under the title and used as the meta description seed. Aim for roughly 120–160 characters.
   */
  subtitle?: string | null;
  /**
   * For translations: the original work's title.
   */
  originalTitle?: string | null;
  /**
   * আপনার নিজের লেখা সারসংক্ষেপ — স্ক্র্যাপ করা ব্যাক-কভার নয়। এটাই পেজটিকে thin content হওয়া থেকে বাঁচায়।
   */
  synopsis: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * সম্পাদকীয় রিভিউ — থিম, কার জন্য বইটি, লেখকের ধারায় এর অবস্থান। কপিরাইটকৃত (Tier D) বইয়ের পেজের মূল কনটেন্ট এটাই।
   */
  review?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * ২–৩ বাক্য: এই বইটি কাদের ভালো লাগবে। কেনার সিদ্ধান্তে অস্বাভাবিক রকম কাজ করে।
   */
  whoShouldRead?: string | null;
  /**
   * The PRINTED book's contents page, as plain text. Not the online reader — reader chapters are their own collection.
   */
  tableOfContents?:
    | {
        title: string;
        page?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * স্মরণীয় লাইন — পাঠকেরা মনে-রাখা লাইন দিয়ে বই খোঁজেন, প্রতিটি উদ্ধৃতি একটি long-tail সার্চ এন্ট্রি পয়েন্ট।
   */
  quotes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Rendered on the page and as FAQPage JSON-LD — for readers and LLM answer engines, not for SERP rows (Google restricted those in 2023).
   */
  faqItems?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  awards?:
    | {
        name: string;
        year?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Film and TV adaptations are high-volume queries in their own right.
   */
  adaptations?:
    | {
        title: string;
        kind?: ('film' | 'tv' | 'web-series' | 'theatre') | null;
        year?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * hasMany on purpose: anthologies, co-authors. Order matters — first is the byline.
   */
  authors: (number | Author)[];
  /**
   * Same collection, different role. NOTE: a public-domain original under an in-copyright translation is still in-copyright as published.
   */
  translator?: (number | null) | Author;
  /**
   * Nullable: public-domain texts you typeset yourself have none.
   */
  publisher?: (number | null) | Publisher;
  /**
   * Every category shelf this book should appear on.
   */
  categories?: (number | Category)[] | null;
  /**
   * Drives the breadcrumb trail. Must also appear in categories above.
   */
  primaryCategory: number | Category;
  /**
   * Leave empty for a standalone book.
   */
  series?: (number | null) | Series;
  /**
   * হিমু #৭ — sorts the series page.
   */
  seriesNumber?: number | null;
  /**
   * The printed edition's own facts, used for the facts strip and the Book schema. All optional — but the ISBN is checksummed, so a typo is caught here rather than by Google.
   */
  bibliographic?: {
    isbn13?: string | null;
    firstPublished?: number | null;
    editionYear?: number | null;
    pages?: number | null;
    language?: ('bn' | 'en' | 'ar' | 'hi' | 'other') | null;
    binding?: ('hardcover' | 'paperback') | null;
    weightGrams?: number | null;
  };
  /**
   * WHY it is distributable, one sentence: "শরৎচন্দ্র মৃত্যু ১৯৩৮, টেক্সট Bengali Wikisource থেকে, ID …". Required to publish any downloadable tier.
   */
  rightsBasis?: string | null;
  /**
   * Tier B: the licence to attribute, e.g. "CC BY-SA 4.0".
   */
  licenceName?: string | null;
  /**
   * Links the licence name on the public page.
   */
  licenceUrl?: string | null;
  /**
   * Where this text was transcribed from, in Bengali, as the reader should see it: "বাংলা উইকিসংকলন", "ইন্টারনেট আর্কাইভ". Public. Fill it in for any book whose text or PDF we serve.
   */
  textSourceName?: string | null;
  /**
   * Deep link to the source page for THIS book, not the site's front page. Links the source name on the public page.
   */
  textSourceUrl?: string | null;
  /**
   * For permitted tier: date, contact, scope, pasted email text, optional uploaded permission document. Never served publicly — logged-in users only.
   */
  rightsEvidence?:
    | {
        date: string;
        contact: string;
        scope?: string | null;
        emailText?: string | null;
        /**
         * Upload the signed permission letter / screenshot here. Stored in the private evidence bucket, not in Media.
         */
        document?: (number | null) | EvidenceFile;
        id?: string | null;
      }[]
    | null;
  /**
   * Set automatically when the book is published. Accountability, not decoration.
   */
  rightsReviewedBy?: (number | null) | User;
  /**
   * "Removed" blocks re-publishing until cleared. Takedown handling: acknowledge fast, remove fast, log everything.
   */
  takedownStatus?: ('none' | 'notice-received' | 'removed') | null;
  /**
   * প্রচ্ছদ (portrait, ~2:3)। Without one, the site falls back to /default-cover.svg on the page and the generated OG image for social previews.
   */
  cover?: (number | null) | Media;
  /**
   * শুধুমাত্র Tier A/B/C বইয়ের জন্য। কপিরাইটকৃত বইতে ফাইল থাকলে বইটি প্রকাশ করা যাবে না — এটি hook দিয়ে আটকানো আছে।
   */
  pdf?: (number | null) | Media;
  /**
   * Only for a PDF hosted somewhere else you have verified is legal (Wikisource, a publisher's own free release). The uploaded file above always wins if both are set.
   */
  pdfExternalUrl?: string | null;
  /**
   * PDF-র পৃষ্ঠাসংখ্যা — ডাউনলোড বাটনে দেখানো হয়।
   */
  pdfPages?: number | null;
  /**
   * ফাইলের আকার (bytes) — বাটনে MB হিসেবে দেখানো হয়, যাতে কেউ মোবাইল ডেটায় ৯০ MB অন্ধভাবে না নামায়।
   */
  pdfSizeBytes?: number | null;
  /**
   * Same rights rule as the PDF. Offered alongside it when present.
   */
  epub?: (number | null) | Media;
  /**
   * PLAIN product URL only, e.g. https://www.rokomari.com/book/1336/shunno — the affiliate parameters are appended at render time from env, never stored. When the program changes you edit one file, not every book.
   */
  rokomariUrl?: string | null;
  /**
   * Rokomari-তে সর্বশেষ দেখা বিক্রয়মূল্য।
   */
  priceBdt?: number | null;
  /**
   * শুধু নিজে দেখে থাকলে দিন — কখনো ডিসকাউন্ট বানিয়ে দেখানো হয় না।
   */
  mrpBdt?: number | null;
  /**
   * দাম কবে যাচাই করা হয়েছে। ৬০ দিনের বেশি পুরোনো হলে পেজে সংখ্যার বদলে “দাম দেখুন” দেখানো হয় — নিয়মটা কম্পোনেন্টে, সম্পাদকের স্মৃতিতে নয়।
   */
  priceCheckedAt?: string | null;
  /**
   * Only claim stock you have checked.
   */
  stockStatus?: ('in-stock' | 'out-of-stock' | 'preorder') | null;
  /**
   * Any other shop that stocks this edition. Rokomari above is the primary.
   */
  otherStores?:
    | {
        name: string;
        url: string;
        price?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Updated by the download beacon, not by editors.
   */
  downloadCount?: number | null;
  /**
   * Denormalised from approved reviews. Never hand-edited.
   */
  ratingAverage?: number | null;
  /**
   * How many approved reviews the average is built from.
   */
  ratingCount?: number | null;
  /**
   * URL segment — /book/opekkha. Lowercase letters, numbers and hyphens only. Changing this after publishing breaks every existing link, so treat it as permanent.
   */
  slug: string;
  /**
   * The compliance gate — the Rights tab holds the evidence for whatever you pick here. public-domain: লেখকের মৃত্যুর ৬০ বছর পার (বাংলাদেশ আইন)। open-licence: CC বা প্রকাশকের উন্মুক্ত লাইসেন্স। permitted: লিখিত অনুমতি ফাইলে আছে। in-copyright: বাকি সব — কোনো PDF নয়, কখনোই।
   */
  rightsTier: 'public-domain' | 'open-licence' | 'permitted' | 'in-copyright';
  /**
   * A future date holds the book back even after publishing — the daily cron brings it live once the date passes.
   */
  publishDate: string;
  /**
   * Hand-picks this book for the "জনপ্রিয়" rail. With nothing flagged, that rail falls back to most recent.
   */
  popular?: boolean | null;
  /**
   * Eligible for the homepage hero shelf.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * One record per writer, and the hub page every byline links to. Death year is the field that matters most: death + 60 years is the Bangladesh public-domain test, so filling it in is what lets a book be classified at all.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  /**
   * বাংলা নাম — হুমায়ূন আহমেদ।
   */
  name: string;
  /**
   * "Humayun Ahmed" — feeds Banglish search and the OG card.
   */
  nameLatin?: string | null;
  /**
   * হুমায়ূন আহমেদ is also searched as "হুমায়ুন আহমেদ", "humayun ahmed" — this array is what makes the site findable.
   */
  nameAliases?:
    | {
        alias: string;
        id?: string | null;
      }[]
    | null;
  /**
   * জীবনী — নিজের ভাষায়, উইকিপিডিয়ার কপি নয়। ১০০ শব্দের কম ও ২টির কম বই হলে পেজটি noindex থাকে।
   */
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Portrait, optional. Used on the author page and in Person JSON-LD.
   */
  photo?: (number | null) | Media;
  /**
   * Year only. Approximate is better than empty.
   */
  birthYear?: number | null;
  /**
   * মৃত্যুসাল — খালি মানে জীবিত। এটি রাইটস-টিয়ার অ্যাসিস্ট্যান্টের ইনপুট: মৃত্যু + ৬০ বছর < বর্তমান বছর হলে পাবলিক ডোমেইন।
   */
  deathYear?: number | null;
  /**
   * District or city, as it would be written in Bengali.
   */
  birthPlace?: string | null;
  /**
   * Feeds Person JSON-LD.
   */
  nationality?: string | null;
  /**
   * Hand-picked highlights shown first on the author page.
   */
  notableWorks?: (number | Book)[] | null;
  /**
   * Wikipedia, official site. Outbound authority links help E-E-A-T and feed Person JSON-LD sameAs.
   */
  externalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * URL segment — /author/humayun-ahmed. Treat as permanent once published.
   */
  slug: string;
  /**
   * Denormalised — maintained by the Books hooks, never hand-edited.
   */
  bookCount?: number | null;
  /**
   * Shown on the homepage author rail.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every public upload — book covers, blog headers, images placed inside a chapter. Files go straight to Cloudflare R2 and are served from there, so anything uploaded here is world-readable the moment it finishes. Permission letters and other private documents belong in Evidence files instead.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Needed only for images placed inside a chapter body, where the picture carries meaning. Cover images are decorative and ignore this; PDFs don't use it at all.
   */
  alt?: string | null;
  /**
   * Optional attribution, if the image came from a source that requires crediting.
   */
  credit?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * One record per publishing house, and the hub page their books link to. Permission status is the outreach pipeline: only a publisher marked Granted can have books moved to the permitted rights tier, and the evidence still goes on the book.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publishers".
 */
export interface Publisher {
  id: number;
  /**
   * বাংলা নাম — আফসার ব্রাদার্স।
   */
  name: string;
  /**
   * "Afsar Brothers" — feeds Banglish search.
   */
  nameLatin?: string | null;
  /**
   * প্রকাশনীর পরিচিতি — পেজটিকে thin হওয়া থেকে বাঁচায়।
   */
  about?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional. Shown on the publisher page.
   */
  logo?: (number | null) | Media;
  /**
   * Year founded, if known.
   */
  establishedYear?: number | null;
  /**
   * Street address, as printed on their books.
   */
  address?: string | null;
  /**
   * Their own site. Full http:// or https:// URL.
   */
  website?: string | null;
  /**
   * Where a permission request goes. Never shown publicly.
   */
  contactEmail?: string | null;
  /**
   * Rokomari's page for this publisher — plain URL, affiliate params are added at render time.
   */
  rokomariPublisherUrl?: string | null;
  /**
   * URL segment — /publisher/afsar-brothers.
   */
  slug: string;
  /**
   * Distribution-permission outreach pipeline. Granted → books can move to the permitted tier (with evidence on the book).
   */
  permissionStatus?: ('none' | 'contacted' | 'granted' | 'refused') | null;
  /**
   * Denormalised — maintained by hooks, never hand-edited.
   */
  bookCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The genre shelves, at most two levels deep (উপন্যাস › ঐতিহাসিক উপন্যাস) — a third level is refused on save. The description is not a caption: a genre page ranks on a real ~150-word introduction and stays a bare grid without one.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * বাংলা নাম — উপন্যাস, কবিতা, ইসলামি বই।
   */
  name: string;
  /**
   * "Uponnash" — feeds Banglish search.
   */
  nameLatin?: string | null;
  /**
   * এই জনরার সত্যিকারের ভূমিকা (~১৫০ শব্দ) — এটিই পেজটিকে র‍্যাংক করায়, খালি গ্রিড করায় না।
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional square image for the homepage category grid.
   */
  icon?: (number | null) | Media;
  /**
   * URL segment — /category/uponnash.
   */
  slug: string;
  /**
   * উপন্যাস › ঐতিহাসিক উপন্যাস। Two levels maximum — enforced on save.
   */
  parent?: (number | null) | Category;
  /**
   * Sort order in navigation. Lower first.
   */
  order?: number | null;
  /**
   * Shown in the homepage category grid.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * A named run of books — হিমু, মিসির আলি, ফেলুদা. You do not add books here: each book joins by setting its own series and series number, and this page sorts by that number.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series".
 */
export interface Series {
  id: number;
  /**
   * বাংলা নাম — হিমু।
   */
  name: string;
  /**
   * "Himu" — feeds Banglish search.
   */
  nameLatin?: string | null;
  /**
   * What holds the run together — the recurring character, the setting, the order to read it in. A series page with no text is a list of covers.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional image for the series page header and the series rail.
   */
  coverImage?: (number | null) | Media;
  /**
   * URL segment — /series/himu.
   */
  slug: string;
  /**
   * The writer of the run. Leave empty for a multi-author series.
   */
  author?: (number | null) | Author;
  /**
   * Denormalised — maintained by hooks, never hand-edited.
   */
  bookCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Permission letters, signed releases and screenshots of a rights holder's email — the audit trail behind every “permitted” book. Unlike Media, these are served through a logged-in route and never from the public bucket, so they stay private. Attach one from a book's Permission evidence block.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evidence-files".
 */
export interface EvidenceFile {
  id: number;
  /**
   * What this document is and who it came from — “Prothoma Prokashon-এর অনুমতি ইমেইল, ১২ মার্চ ২০২৬”. The filename is rarely enough a year later.
   */
  description?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * Everyone who can log in and edit the site. There are no roles yet, so every account here can publish, unpublish and delete anything — invite accordingly. You cannot delete your own account, which is what stops the last login being removed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Display name, used for the byline on chapters you write.
   */
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * One document per chapter of a full text we may legally republish, each its own page at /book/<book>/read/<chapter>. Only public-domain and open-licence books accept chapters — permitted does not, because permission to hand out a PDF is not permission to republish the work as HTML here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "book-chapters".
 */
export interface BookChapter {
  id: number;
  /**
   * অধ্যায়ের শিরোনাম, e.g. "প্রথম পরিচ্ছেদ" or the chapter's own name.
   */
  title: string;
  /**
   * অধ্যায়ের সম্পূর্ণ টেক্সট। Source and fidelity note goes in the book's rightsBasis, not here.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Which book this chapter belongs to. Saving against a book whose rights tier forbids full text is refused, in both directions.
   */
  book: number | Book;
  /**
   * Orders the reader navigation. 1-based.
   */
  chapterNumber: number;
  /**
   * Shown as reading time. Nothing fills this in for you: copy the live count from under the body. Left empty, the chapter's own page still computes it, but the chapter list on the book's reading page shows 0 min, because that list is built without the body text.
   */
  wordCount?: number | null;
  /**
   * URL segment: /book/<book>/read/<slug>. Lowercase letters, numbers and hyphens only. Unique within the book.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Curated lists and buying guides — the best-converting page type on the site, because a reader who opens one has already decided to buy something. Each entry needs a note saying why the book is on the list; three entries is the minimum and the note is the whole value. A book may be added as a draft with nothing but a title, so writing the list is never blocked on ten unwritten synopses.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lists".
 */
export interface List {
  id: number;
  /**
   * তালিকার শিরোনাম — "১০টি সেরা মুক্তিযুদ্ধের বই"।
   */
  title: string;
  /**
   * ভূমিকা: কে এই তালিকাটি চাইবে, বাছাইয়ের মানদণ্ড কী। এটিই পেজকে র‍্যাংক করায়।
   */
  intro: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * ক্রম অনুযায়ী বই — প্রতিটির সাথে কেন-এই-বইটি নোট।
   */
  entries: {
    /**
     * খসড়া বইও চলবে: শুধু শিরোনাম দিয়ে সেভ করা বই যোগ করেও তালিকা প্রকাশ করা যাবে, বইটি তখন ড্যাশবোর্ডের Needs attention তালিকায় থাকবে। খেয়াল রাখুন, খসড়া বইয়ের শিরোনাম, লেখক ও প্রচ্ছদ তালিকার পেজে পাঠক দেখতে পাবেন — শুধু বইয়ের নিজের পেজের লিংক থাকবে না।
     */
    book: number | Book;
    /**
     * কেন এই বইটি তালিকায় — নোটটাই পেজের মূল্য, তালিকাটা শুধু কাঠামো।
     */
    note: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  /**
   * Optional header image for the list page and the guides rail.
   */
  coverImage?: (number | null) | Media;
  /**
   * URL segment — /list/muktijuddho-shera-boighor.
   */
  slug: string;
  /**
   * A future date holds the list back until it passes.
   */
  publishDate: string;
  /**
   * Shown on the homepage guides rail.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Prose at /blog/<slug> — author retrospectives, বইমেলা coverage, reading-culture pieces. Use a reading list instead when the piece is really a ranked set of books; a post is writing that happens to mention books, and the ones you link render as a rail beside the text.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  /**
   * The headline, in Bengali. Also the <h1> and the SERP title.
   */
  title: string;
  /**
   * Meta description and card text. ~120–160 characters.
   */
  summary?: string | null;
  /**
   * The article itself.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Header image, also used for the social card.
   */
  coverImage?: (number | null) | Media;
  /**
   * URL segment — /blog/boimela-2026.
   */
  slug: string;
  /**
   * Books referenced by the post — rendered as the "এই লেখায় যে বইগুলো" rail. A draft book with nothing but a title can go here too: the post publishes, the book waits in the dashboard's Needs attention list, and its title and cover show in the rail without a link.
   */
  relatedBooks?: (number | Book)[] | null;
  /**
   * A future date holds the post back until it passes.
   */
  publishDate: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The site's own fixed pages — About, Contact, Privacy Policy, Disclosure, DMCA — living at the top level, e.g. /about. A slug that collides with a route the app already owns is refused on save, because a static segment always wins in Next's matcher and the page would simply never appear.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Shown as the page heading and in the browser tab.
   */
  title: string;
  /**
   * URL segment — /about, /contact, /privacy-policy. Lowercase letters, numbers and hyphens only.
   */
  slug: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The moderation queue. Approving a review publishes it immediately, with no deployment in between, and folds its stars into the book's average — so this is the one screen on the site where a save is instantly visible to readers. Nothing arrives here approved.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  /**
   * Only Approved reviews show on the public page and count toward the book's rating.
   */
  status: 'pending' | 'approved' | 'spam';
  /**
   * The book this review was left on.
   */
  book: number | Book;
  /**
   * 1–5 stars, integer.
   */
  rating: number;
  /**
   * Shown publicly beside the review.
   */
  authorName: string;
  /**
   * Optional, private. Never displayed on the site.
   */
  authorEmail?: string | null;
  /**
   * The review text. Rendered as plain text on the page.
   */
  body: string;
  /**
   * Salted hash of the submitter's IP, used for rate limiting. Not the address itself.
   */
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'books';
        value: number | Book;
      } | null)
    | ({
        relationTo: 'book-chapters';
        value: number | BookChapter;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'publishers';
        value: number | Publisher;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'series';
        value: number | Series;
      } | null)
    | ({
        relationTo: 'lists';
        value: number | List;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'evidence-files';
        value: number | EvidenceFile;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  title?: T;
  titleLatin?: T;
  subtitle?: T;
  originalTitle?: T;
  synopsis?: T;
  review?: T;
  whoShouldRead?: T;
  tableOfContents?:
    | T
    | {
        title?: T;
        page?: T;
        id?: T;
      };
  quotes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  awards?:
    | T
    | {
        name?: T;
        year?: T;
        id?: T;
      };
  adaptations?:
    | T
    | {
        title?: T;
        kind?: T;
        year?: T;
        id?: T;
      };
  authors?: T;
  translator?: T;
  publisher?: T;
  categories?: T;
  primaryCategory?: T;
  series?: T;
  seriesNumber?: T;
  bibliographic?:
    | T
    | {
        isbn13?: T;
        firstPublished?: T;
        editionYear?: T;
        pages?: T;
        language?: T;
        binding?: T;
        weightGrams?: T;
      };
  rightsBasis?: T;
  licenceName?: T;
  licenceUrl?: T;
  textSourceName?: T;
  textSourceUrl?: T;
  rightsEvidence?:
    | T
    | {
        date?: T;
        contact?: T;
        scope?: T;
        emailText?: T;
        document?: T;
        id?: T;
      };
  rightsReviewedBy?: T;
  takedownStatus?: T;
  cover?: T;
  pdf?: T;
  pdfExternalUrl?: T;
  pdfPages?: T;
  pdfSizeBytes?: T;
  epub?: T;
  rokomariUrl?: T;
  priceBdt?: T;
  mrpBdt?: T;
  priceCheckedAt?: T;
  stockStatus?: T;
  otherStores?:
    | T
    | {
        name?: T;
        url?: T;
        price?: T;
        id?: T;
      };
  downloadCount?: T;
  ratingAverage?: T;
  ratingCount?: T;
  slug?: T;
  rightsTier?: T;
  publishDate?: T;
  popular?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "book-chapters_select".
 */
export interface BookChaptersSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  book?: T;
  chapterNumber?: T;
  wordCount?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  nameLatin?: T;
  nameAliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  bio?: T;
  photo?: T;
  birthYear?: T;
  deathYear?: T;
  birthPlace?: T;
  nationality?: T;
  notableWorks?: T;
  externalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  slug?: T;
  bookCount?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publishers_select".
 */
export interface PublishersSelect<T extends boolean = true> {
  name?: T;
  nameLatin?: T;
  about?: T;
  logo?: T;
  establishedYear?: T;
  address?: T;
  website?: T;
  contactEmail?: T;
  rokomariPublisherUrl?: T;
  slug?: T;
  permissionStatus?: T;
  bookCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  nameLatin?: T;
  description?: T;
  icon?: T;
  slug?: T;
  parent?: T;
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series_select".
 */
export interface SeriesSelect<T extends boolean = true> {
  name?: T;
  nameLatin?: T;
  description?: T;
  coverImage?: T;
  slug?: T;
  author?: T;
  bookCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lists_select".
 */
export interface ListsSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  entries?:
    | T
    | {
        book?: T;
        note?: T;
        id?: T;
      };
  coverImage?: T;
  slug?: T;
  publishDate?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  body?: T;
  coverImage?: T;
  slug?: T;
  relatedBooks?: T;
  publishDate?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  status?: T;
  book?: T;
  rating?: T;
  authorName?: T;
  authorEmail?: T;
  body?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evidence-files_select".
 */
export interface EvidenceFilesSelect<T extends boolean = true> {
  description?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Name, tagline, social links and homepage shelves. Saving triggers a rebuild; the change is live when that deployment finishes (usually a couple of minutes).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Shown in the header, footer and page titles.
   */
  siteName: string;
  /**
   * Short line under the site name on the homepage hero.
   */
  tagline?: string | null;
  /**
   * Fallback meta description for pages that do not compute their own. One or two sentences.
   */
  siteDescription?: string | null;
  /**
   * Fallback social-share image (1200×630) used when a page has no image of its own.
   */
  defaultOgImage?: (number | null) | Media;
  /**
   * Optional single book spotlighted at the top of the homepage. Leave empty for the default hero.
   */
  heroBook?: (number | null) | Book;
  /**
   * Up to three curated lists promoted on the homepage.
   */
  featuredLists?: (number | List)[] | null;
  /**
   * Categories shown in the homepage browse strip, in this order.
   */
  featuredCategories?: (number | Category)[] | null;
  /**
   * Footer social links, in display order.
   */
  socialLinks?:
    | {
        /**
         * e.g. Facebook, YouTube, X
         */
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown on the contact page and in DMCA notices.
   */
  contactEmail?: string | null;
  /**
   * Optional extra line in the footer (e.g. a mission statement). Copyright line is automatic.
   */
  footerNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Buy-button labels and the mandatory affiliate disclosure line. Every string here renders on every book page, so saving triggers a rebuild and the change is live when that deployment finishes. The affiliate ID itself is configured by the developer, not here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-settings".
 */
export interface AffiliateSetting {
  id: number;
  /**
   * Master switch. Off = buy buttons still render but link to plain Rokomari URLs without affiliate parameters.
   */
  affiliateEnabled?: boolean | null;
  /**
   * Label on the primary buy button (green).
   */
  buyButtonLabel: string;
  /**
   * Label on the free-PDF download button (blue).
   */
  downloadButtonLabel: string;
  /**
   * Legally required disclosure shown near every affiliate link. Do not remove — only reword.
   */
  disclosureText: string;
  /**
   * Heading of the panel shown after a reader clicks a free-PDF download.
   */
  postDownloadHeading?: string | null;
  /**
   * Supporting line in the post-download panel.
   */
  postDownloadBody?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  siteDescription?: T;
  defaultOgImage?: T;
  heroBook?: T;
  featuredLists?: T;
  featuredCategories?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  contactEmail?: T;
  footerNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-settings_select".
 */
export interface AffiliateSettingsSelect<T extends boolean = true> {
  affiliateEnabled?: T;
  buyButtonLabel?: T;
  downloadButtonLabel?: T;
  disclosureText?: T;
  postDownloadHeading?: T;
  postDownloadBody?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}